### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by parnz** [MekayelAnik/ispyagentdvr-docker#1]
Agent crash randomly.

`/AgentDVR/Agent.sh: line 6:    11 Segmentation fault      (core dumped) /AgentDVR/Agent`

My docker host is 
`Linux docker 5.10.0-23-amd64 #1 SMP Debian 5.10.179-3 (2023-07-27) x86_64 GNU/Linux`

**Comment by MekayelAnik** [comment]
I couldn't reproduce your problem. 
I have the "latest" tag running on my "ARMHF" as well as "x86_64". All are running fine.
I am running: Docker version 24.0.5, build ced0996
Bookworm ( Kernel:6.1.0-10-amd64) on x86_64
and Debian Bullseye (Kernel: 6.1.21-v8+) on aarch64
You can uninstall and remove ` /var/lib/docker ` as well as `/var/lib/containerd` then install docker using:
`sudo apt-get update
sudo apt-get install ca-certificates curl gnupg
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
 sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin`
Please let me know your update.

**Comment by parnz** [comment]
same result.

here is my docker-compose.yml if needed.

```
version: "3.9"

networks:
  proxy:
    external: true

services:
  agentdvr:
    build:
      context: ./stable-image-builder
      dockerfile: Dockerfile
    image: local/ispyagentdvr
    container_name: AgentDVR
    hostname: agentdvr
    privileged: true
    restart: unless-stopped
    devices:
      - /dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Bangkok
    volumes:
      - ./config/:/AgentDVR/Media/XML/
      - ./commands:/AgentDVR/Commands/
      - /mnt/hd1/:/AgentDVR/Media/WebServerRoot/Media/ 
    network_mode: host
    
  CodeProjectAI:
    image: codeproject/ai-server:gpu
    container_name: CodeProjectAI-Server
    hostname: ai-server
    restart: unless-stopped
    devices:
      - /dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
    volumes:
      - ./ai/:/etc/codeproject/ai
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 32168:32168
    networks:
      - proxy
```

then build using:

```
docker-compose build agentdvr
docker-compose up -d
docker image prune -af
```
All volume directories on the host are owned by root

Thank you.
