### ISSUE TITLE
AgentDVR does not seem to respect Docker PUID/PGID

### ISSUE THREAD

**Issue by Orange-418** [MekayelAnik/ispyagentdvr-docker#14]
After composing the container, AgentDVR service does not appear to respect the PUID=1000 PGID=1000 announced in the docker-compose (or cli).

It appears to save files as root onto the shared volumes regardless, and does not even create a corresponding user inside the container.

This can be worked around by manually creating the group and user in the Dockerfile, and then forcing the container to use it in the composition commands as follows:

````
# Bottom of Dockerfile in latest-image-builder

RUN groupadd -f -g 1000 agentdvr && \
    useradd -m -d /home/agentdvr -s /bin/bash -g 1000 -u 1000 agentdvr || true && \
    chown -R agentdvr:agentdvr /AgentDVR && \
    chmod 777 -R /AgentDVR
````

````
# Corresponding docker-compose.yml file
---
services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:latest
    container_name: ispyagentdvr
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8090 
      - TZ=Asia/Dhaka
    volumes:
      - /path/to/config:/AgentDVR/Media/XML
      - /path/to/recordings:/AgentDVR/Media/WebServerRoot/Media
      - /path/to/commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50010:50000-50010/udp
    restart: unless-stopped
````
