### ISSUE TITLE
Doesn't appear to work on local network.

### ISSUE THREAD

**Issue by MicahZoltu** [MekayelAnik/ispyagentdvr-docker#23]
I managed to get everything setup and working such that I can access the web UI from the docker host, but no other devices on my local network are able to reach it.  The web UI loads but it cannot establish a WebRTC connection with the backend and eventually complains about "No Local ICE"".  I am on Windows so I cannot setup a docker macvlan.

After many hours of troubleshooting, the problem seems to be centered around the TURN/STUN/ICE server.  It is unclear to me why this complication is necessary and why the server doesn't just listen on some ports and be accessed like any other IP endpoint out there.  I suspect the answer may be "that is an issue with AgentDVR, not specific to the docker image" but this problem doesn't exist when Agent DVR is run outside of docker so I figured I would try here first (though, I think the reason the problem doesn't exist outside of docker is because of the weird TURN/STUN/ICE stuff).

**Comment by MicahZoltu** [comment]
When I look at about:webrtc in my browser I can see both the docker host browser *and* the other device on my LAN trying to connect to the container's internal IP address.  Is there some way I can tell Agent DVR to advertise the docker host's address instead of the container's address?  I believe this would resolve the problem (and also maybe remove the need for the TURN/ICE stuff).

**Comment by MekayelAnik** [comment]
Please share the docker compose file or CLI cmd & what is your docker host ip and via which IP you are trying to access the webUI.

**Comment by MicahZoltu** [comment]
Docker Host IP: 192.168.50.7
Docker Container IP: 172.18.0.2
Web UI accessed via: http://192.168.50.7:8090/

```yml
services:
  agent-dvr:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: 'mekayelanik/ispyagentdvr:vlc-hwaccel-5.5.4.0-01062024@sha256:dbe82e366c64f853015ea5a7ccee752705ab7fc4fae6c0508b20acfd1e446ebf'
    container_name: 'agent-dvr'
    environment:
      # PUID: '1000'
      # PGID: '1000'
      WEBUI_PORT: '8090'
      TZ: 'Asia/Singapore'
      NVIDIA_VISIBLE_DEVICES: 'all'
    volumes:
      - config:/AgentDVR/Media/XML
      - /path/to/recordings:/AgentDVR/Media/WebServerRoot/Media
      - commands:/AgentDVR/Commands
    ports:
      - '8090:8090'
      - '3478:3478/udp'
      - '50000-50010:50000-50010/udp'
    restart: 'unless-stopped'

volumes:
  config:
  commands:
```
