### ISSUE TITLE
Failed to create secure directory (/root/.config/pulse): Permission denied

### ISSUE THREAD

**Issue by Figgueh** [MekayelAnik/ispyagentdvr-docker#27]
Currently trying to setup the DVR with this docker compose file:
```
version: "2.1"
services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:latest
    container_name: ispyagentdvr
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8090 
      - TZ=Canada/Eastern
    volumes:
      - /mnt/DVR/config:/AgentDVR/Media/XML
      - /mnt/DVR/recordings:/AgentDVR/Media/WebServerRoot/Media
      - /mnt/DVR/commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50010:50000-50010/udp
    restart: unless-stopped
```

Here is the log for the container:
```
cat: /AgentDVR/Media/XML/current_port.txt: No such file or directory
 Current AgentDVR Docker Image: 5.6.6.0
 If this Container is deployed on a Docker-Macvlan or Docker-IPvlan Network, then the IP Address of this AgentDVR container is: 172.18.0.4, Otherwise the AgentDVR IP is the IP of your HOST Server IP or localhost if you are accessing the WebUI from a Browser on the HOST Server.
 AgentDVR WebUI can be accessed on PORT: 
 Therefore Most Probable AgentDVR WebUI Address: 172.18.0.4: or Your-HOST-Server-IP: or localhost:
 iSpy Agent DVR is free to use locally for private use. You can add as many cameras as you like.
 SSL secured web access, SMS, Twitter, email alerts, mobile device access, cloud uploads, Virtual Reality and other services that use iSpy Agent DVR online platform require a subscription or an annual payment.
 If you desire to obtain a Subscription plan or want a Business License, please visit https://www.ispyconnect.com/pricing.aspx
cat: /usr/bin/share/base-image-timestamp: No such file or directory
This docker image was built at: Thu Aug 15 02:28:48 +06 2024 : Bangladesh Time (UTC+06)
This Container was started on: Tue Aug 20 17:47:38 EDT 2024
usermod: no changes
Failed to create secure directory (/root/.config/pulse): Permission denied
```

All volumes where created by the user 1000. 
Changing the PUID and PGID to 0 removes this issue, but I feel like running the container as root is more of a hack then a solution.
Also, changing them to 0 still doesn't allow me to access the webUI.

That first message: `cat: /AgentDVR/Media/XML/current_port.txt: No such file or directory' presists.`
I tried creating this file and putting 8090 in that text file. but still doesnt work.

Applying my patches results in docker compose file and this log:
compose file:
```
version: "2.1"
services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:latest
    container_name: ispyagentdvr
    environment:
      - PUID=0
      - PGID=0
      - WEBUI_PORT=8090 
      - TZ=Canada/Eastern
    volumes:
      - /mnt/DVR/config:/AgentDVR/Media/XML
      - /mnt/DVR/recordings:/AgentDVR/Media/WebServerRoot/Media
      - /mnt/DVR/commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50010:50000-50010/udp
    restart: unless-stopped
```

log file:
```
Current AgentDVR Docker Image: 5.6.6.0
 If this Container is deployed on a Docker-Macvlan or Docker-IPvlan Network, then the IP Address of this AgentDVR container is: 172.18.0.4, Otherwise the AgentDVR IP is the IP of your HOST Server IP or localhost if you are accessing the WebUI from a Browser on the HOST Server.
 AgentDVR WebUI can be accessed on PORT: 8090
 Therefore Most Probable AgentDVR WebUI Address: 172.18.0.4:8090 or Your-HOST-Server-IP:8090 or localhost:8090
 iSpy Agent DVR is free to use locally for private use. You can add as many cameras as you like.
 SSL secured web access, SMS, Twitter, email alerts, mobile device access, cloud uploads, Virtual Reality and other services that use iSpy Agent DVR online platform require a subscription or an annual payment.
 If you desire to obtain a Subscription plan or want a Business License, please visit https://www.ispyconnect.com/pricing.aspx
cat: /usr/bin/share/base-image-timestamp: No such file or directory
This docker image was built at: Thu Aug 15 02:28:48 +06 2024 : Bangladesh Time (UTC+06)
This Container was started on: Tue Aug 20 17:59:58 EDT 2024
The vlaue of PUID is 0 which is NOT in Valid Range (Greater than or Equal to 1000 & Less than or Equal to 2147483647). Running AgentDVR as root...
The vlaue of PGID is 0 which is NOT in Valid Range (Greater than or Equal to 1000 & Less than or Equal to 2147483647). Running AgentDVR as root...
PUID/PGID is NOT SET thus Running AgentDVR as root...
```

webUI is still not accessible.
localhost:8090
172.18.0.4:8090
[HOSTIP]:8090

None of these addresses work.
