### ISSUE TITLE
Make local camera and microphone available to docker container

### ISSUE THREAD

**Issue by RichardBronosky** [MekayelAnik/ispyagentdvr-docker#29]
I have managed to get my laptop camera to be available as a source with the following `docker-compose.yaml`

```
---
version: "3.9"
services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:latest
    container_name: ispyagentdvr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./user/config:/AgentDVR/Media/XML
      - ./user/recordings:/AgentDVR/Media/WebServerRoot/Media
      - ./user/commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50010:50000-50010/udp
    devices:
      - /dev/video0
      - /dev/snd
    restart: unless-stopped

```

This is because `/dev/video0` is working as expected, just as it does with the following local cli test:

```
mplayer tv:// -tv driver=v4l2:device=/dev/video1:width=1280:height=720:fps=30:outfmt=yuy2
```

However, the `/dev/snd` does not work to make the microphone available.

Any suggestions on how to do this?
