### ISSUE TITLE
SSL port env variable?

### ISSUE THREAD

**Issue by Mr-Newlove** [MekayelAnik/ispyagentdvr-docker#30]
Hello, I have been attempting to get SSL working inside this container.

I can't find any errors in the log related to anything being wrong with my certificate and the section of the log where it start listing on different interfaces do not show any HTTPS activity.

```
23:00:47 LocalServerPort: Using default port (8090)
23:00:47 InitServer: Access locally at http://localhost:8090/
23:00:47 StartUp: LogLevel: Debug
23:00:47 Initialize_OnInitialized: Running at http://localhost:8090/
23:00:47 AddressListIPv4: IP addresses:
23:00:47 AddressListIPv4: 172.16.2.3
23:00:47 Listen: Exception has been thrown by the target of an invocation.    at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at CoreLogic.LocalServer.AgentDVRServer.Listen()
23:00:47 Listen: Address already in use    at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
23:00:47 Listen: Accepting http connections at http://*:8090/
23:00:47 ScanNetwork: No network devices found
```

I have specified a SSL port in the AgentDVR interface, selected my cert and password, rebooted and regenerated the key many different ways and this is the last thing I can think of.

I have also tried setting the SSL port to 443 in AgentDVR and forwarded that port in docker, log does not change from above

Is there an environment variable to actually enable the SSL functionality?

**Comment by ispysoftware** [comment]
That's saying that the address/ SSL port is already in use

**Comment by Mr-Newlove** [comment]
Making this comment from my phone, I turned my computer off and went to bed, didn't expect a response that fast tonight. :)

Is there any way to have AgentDVR attempt to open on a different port? Like 8091?

This is my container setup in TrueNAS:

```
services:
  codeprojectai:
    container_name: CodeProject.AI-Server
    image: codeproject/ai-server
    ports:
      - '8092:32168'
    volumes:
      - /mnt/main-lts/truenas-apps/codeprojectai/ai:/etc/codeproject/ai
      - /mnt/main-lts/truenas-apps/codeprojectai/modules:/app/modules
  ispyagentdvr:
    container_name: ispyagentdvr
    environment:
      - PUID=1000
      - PGID=1000
      - AGENTDVR_WEBUI_PORT=8090
      - TZ=America/Los_Angeles
    image: mekayelanik/ispyagentdvr:latest
    ports:
      - '8091:8091'
      - '8090:8090'
      - 3478:3478/udp
      - 50000-50100:50000-50100/udp
    restart: unless-stopped
    volumes:
      - /mnt/main-lts/truenas-apps/ispyagentdvr/config:/AgentDVR/Media/XML
      - >-
        /mnt/main-lts/truenas-apps/ispyagentdvr/recordings:/AgentDVR/Media/WebServerRoot/Media
      - /mnt/main-lts/truenas-apps/ispyagentdvr/commands:/AgentDVR/Commands
      - /mnt/NVR/NVR-data:/media/NVR-data
      - /mnt/main-lts/truenas-apps/certs:/media/certs
```

Server setup in AgentDVR below:

![Image](https://github.com/user-attachments/assets/0b4d9507-e4cd-44aa-a0a0-c38715444e42)

**Comment by MekayelAnik** [comment]
Use Environment variable,
`AGENTDVR_WEBUI_PORT=8091`

> Making this comment from my phone, I turned my computer off and went to bed, didn't expect a response that fast tonight. :)
> 
> Is there any way to have AgentDVR attempt to open on a different port? Like 8091?
> 
> This is my container setup in TrueNAS:
> 
> ```
> services:
>   codeprojectai:
>     container_name: CodeProject.AI-Server
>     image: codeproject/ai-server
>     ports:
>       - '8092:32168'
>     volumes:
>       - /mnt/main-lts/truenas-apps/codeprojectai/ai:/etc/codeproject/ai
>       - /mnt/main-lts/truenas-apps/codeprojectai/modules:/app/modules
>   ispyagentdvr:
>     container_name: ispyagentdvr
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - AGENTDVR_WEBUI_PORT=8090
>       - TZ=America/Los_Angeles
>     image: mekayelanik/ispyagentdvr:latest
>     ports:
>       - '8091:8091'
>       - '8090:8090'
>       - 3478:3478/udp
>       - 50000-50100:50000-50100/udp
>     restart: unless-stopped
>     volumes:
>       - /mnt/main-lts/truenas-apps/ispyagentdvr/config:/AgentDVR/Media/XML
>       - >-
>         /mnt/main-lts/truenas-apps/ispyagentdvr/recordings:/AgentDVR/Media/WebServerRoot/Media
>       - /mnt/main-lts/truenas-apps/ispyagentdvr/commands:/AgentDVR/Commands
>       - /mnt/NVR/NVR-data:/media/NVR-data
>       - /mnt/main-lts/truenas-apps/certs:/media/certs
> ```
> 
> Server setup in AgentDVR below:
> 
> ![Image](https://github.com/user-attachments/assets/0b4d9507-e4cd-44aa-a0a0-c38715444e42)

Use Environment variable,
`AGENTDVR_WEBUI_PORT=8091`
It is used to change the AgentDVR webui port.
This is not a issue with the container, so i am closing the issue.
If you have further query, feel free to leave comments. You can also visit reddit handle of AgentDVR. There you can have discussion and troubleshooting with large community.

**Comment by Mr-Newlove** [comment]
Odd, the AgentDVR setup I am using has all the same settings previously used in a TrueCharts(depreciated) and I am trying to get this working property in the new TrueNAS app system.

Modifying to `AGENTDVR_WEBUI_PORT=8091`

Below:
```
services:
  codeprojectai:
    container_name: CodeProject.AI-Server
    image: codeproject/ai-server
    ports:
      - '8092:32168'
    volumes:
      - /mnt/main-lts/truenas-apps/codeprojectai/ai:/etc/codeproject/ai
      - /mnt/main-lts/truenas-apps/codeprojectai/modules:/app/modules
  ispyagentdvr:
    container_name: ispyagentdvr
    environment:
      - PUID=1000
      - PGID=1000
      - AGENTDVR_WEBUI_PORT=8091
      - TZ=America/Los_Angeles
    image: mekayelanik/ispyagentdvr:latest
    ports:
      - '8091:8091'
      - '8090:8090'
      - 3478:3478/udp
      - 50000-50100:50000-50100/udp
    restart: unless-stopped
    volumes:
      - /mnt/main-lts/truenas-apps/ispyagentdvr/config:/AgentDVR/Media/XML
      - >-
        /mnt/main-lts/truenas-apps/ispyagentdvr/recordings:/AgentDVR/Media/WebServerRoot/Media
      - /mnt/main-lts/truenas-apps/ispyagentdvr/commands:/AgentDVR/Commands
      - /mnt/NVR/NVR-data:/media/NVR-data
      - /mnt/main-lts/truenas-apps/certs:/media/certs
```

WebUI still only rendering on port 8090

![Image](https://github.com/user-attachments/assets/90308701-6aca-4544-8515-2b34b6069653)

With this error for https on port 8091

![Image](https://github.com/user-attachments/assets/476976c7-4e17-4436-b967-ba957187386b)

Local server still set the same in Agent DVR:

![Image](https://github.com/user-attachments/assets/f8806846-949a-4cd2-a44b-b45b3dad6348)

With the same event log:

```
16:51:26 LocalServerPort: Using default port (8090)
16:51:26 InitServer: Access locally at http://localhost:8090/
16:51:26 StartUp: LogLevel: Debug
16:51:26 Initialize_OnInitialized: Running at http://localhost:8090/
16:51:26 AddressListIPv4: IP addresses:
16:51:26 AddressListIPv4: 172.16.2.3
16:51:26 Listen: Exception has been thrown by the target of an invocation.    at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at CoreLogic.LocalServer.AgentDVRServer.Listen()
16:51:26 Listen: Address already in use    at System.Net.HttpEndPointManager.GetEPListener(String host, Int32 port, HttpListener listener, Boolean secure)
16:51:26 Listen: Accepting http connections at http://*:8090/
16:51:26 ScanNetwork: No network devices found
```


How sure are you this is not a container issue? even with the environment variable set to 8091 as per my configuration for SSL it sill opens regular http on 8090?

Thank you for your time. :)
